### ISSUE TITLE
Failed to find OslExecuteTransition

### ISSUE THREAD

**Issue by ahmetabdi** [btbd/umap#1]
Windows 10 Pro, Version 1909, 18363.778

30GB USB formatted to FAT32

Contains F:\EFI\Boot\bootx64.efi from pre-compiled release

Seems to fail here: https://github.com/btbd/umap/blob/c19878fcfe7d64a79cfc29f45ac0866c9a85f408/boot/main.c#L117

```
umap.exe driver.sys
Failed to communicate with the mapper
```

Error happends on boot:

![Error](https://i.imgur.com/OwDqPuy.png)

**Comment by btbd** [comment]
Thanks for letting me know. My 1909 VM is not the latest and I assumed the signature would not change. I'll push a fix later today.

**Comment by btbd** [comment]
@ahmetabdi I've just tested on the same Windows version (1909 build 18363.778) and on 1909 build 18363.815, and it is able to find the signature. Would you mind sending me your `winload.efi`?

**Comment by ahmetabdi** [comment]
@btbd Thanks for looking into it I will try a couple more times 

Here is the `winload.efi` http://dl.free.fr/getfile.pl?file=/Cz6NWBFX

**Comment by ahmetabdi** [comment]
🤔 just reformatted the USB and now it's working 🤷‍♂️ sorry for the time waste

**Comment by nerded1337** [comment]
@btbd fast boot is the culprit in this case.

**Comment by btbd** [comment]
@nerded1337 Makes sense that fast startup would cause this. Thanks for letting me know.
