### ISSUE TITLE
KERNEL SECURITY CHECK FAILURE on Windows 10 2004

### ISSUE THREAD

**Issue by Xniveres** [btbd/umap#12]
Hey,
I've used the release files and booted the EFI bootloader over Vmware,

I'm using a driver with no Driver object what just outputs a test string.

Once running umap with the driver I get a bluescreen with the following error: KERNEL SECURITY CHECK FAILURE

Could you provide an example driver, or is there a windows setting that has to be changed?

**Comment by xenu1** [comment]
is secureboot off?

**Comment by btbd** [comment]
@Xniveres Set a custom entrypoint instead of Fx/GsDriverEntry and disable stack security check.
