### ISSUE TITLE
Failed to find the Windows EFI bootloader

### ISSUE THREAD

**Issue by T-thanha** [btbd/umap#5]
How to use it ?
Boot usb with no uefi and use command umap driver.sys or boot success restart use cmd run administrators umap driver.sys ? Or more

Run with uefi 
Failed to find the Windows EFI bootloader

**Comment by T-thanha** [comment]
![B66D69EE-74EE-4CF6-BD04-491754F3F786](https://user-images.githubusercontent.com/32900204/85236830-9f840e00-b44b-11ea-8161-eb4a2ad29c5b.jpeg)

**Comment by btbd** [comment]
@autkub101 Can you send the output of `bcdedit` from a terminal?

**Comment by T-thanha** [comment]
Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume1
path                    \efi\microsoft\boot\bootmgfw.efi
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {9cd5af37-b438-11ea-a5d9-a379ad374238}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \WINDOWS\system32\winload.exe
description             Windows 10
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {f033339d-aae1-11ea-91da-a022692fe1bd}
displaymessageoverride  Recovery
recoveryenabled         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \WINDOWS
resumeobject            {9cd5af37-b438-11ea-a5d9-a379ad374238}
nx                      OptIn
bootmenupolicy          Standard

**Comment by btbd** [comment]
> path \WINDOWS\system32\winload.exe

It appears you are running a BIOS installation, which will not work with a UEFI bootkit.

However, it is interesting that Windows says it has a boot manager entry on the EFI system partition, yet the boot loader is still `winload.exe` as if it is a legacy system being loaded by the bootmgr stub.

**Comment by T-thanha** [comment]
> > path \WINDOWS\system32\winload.exe
> 
> It appears you are running a BIOS installation, which will not work with a UEFI bootkit.
> 
> However, it is interesting that Windows says it has a boot manager entry on the EFI system partition, yet the boot loader is still `winload.exe` as if it is a legacy system being loaded by the bootmgr stub.

do you have a fix?

**Comment by btbd** [comment]
@autkub101 You can convert your existing Windows installation to UEFI.

**Comment by T-thanha** [comment]
Thx you
