### ISSUE TITLE
Valorant update!!! not working

### ISSUE THREAD

**Issue by autkub101** [btbd/umap#6]
pls update

how to buid uefi vs2019?
i want to try update my self
how to setup edk2?

**Comment by btbd** [comment]
@autkub101 I looked into it and Vanguard calls ExGetFirmwareEnvironmentVariable with BootCurrent to determine if a suspicious boot entry was loaded. Simply faking the variable appears to work, see 7113189336539cc57493588671bfd4b05c532769.
